name: setup-tfcmt test

on: push

jobs:
  setup-tfcmt-test:
    runs-on: ubuntu-latest
    steps:
      - uses: shirakiya/setup-tfcmt@v1
      - name: Check tfcmt command
        run: |
          which tfcmt
          tfcmt --version
