name: setup-tfcmt test

on: push

jobs:
  action-test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-tfcmt@v1
      - name: Check tfcmt command
        run: |
          which tfcmt
          tfcmt --version
